[env:rp2040zero]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = waveshare_rp2040_zero
framework = arduino
board_build.core = earlephilhower

; USB stack must be TinyUSB for USB-MIDI
build_flags =
    -DUSE_TINYUSB

; Libraries
lib_deps =
    adafruit/Adafruit TinyUSB Library@^3.4.0
    fortyseveneffects/MIDI Library@^5.0.2

; Ignore SdFat issues (not needed for MIDI)
lib_ignore = SdFat - Adafruit Fork

; Upload method
upload_protocol = picotool

; Monitor
monitor_speed = 115200
